KS-2-5 print difficult pay from second lesson task5
iarimx/KotlinSpirit pull request #17
Opened 2023-09-12 12:24 UTC by iarimx

2023-09-12 15:26 UTC, ievetrov requested changes
небольшая доработка

2023-09-12 15:26 UTC, ievetrov commented on src/main/kotlin/lesson_2/lesson_2_task5.kt
> +    val percent: Double = 0.167
отлично, однако, все же корректнее инициализировать значения из ТЗ "как есть". а уже потом модифицировать в коде) потому что предполагаем, что именно в таком виде они приходят из базы

2023-09-12 15:26 UTC, ievetrov commented on src/main/kotlin/lesson_2/lesson_2_task5.kt
> +    val sumFinale = sum * (1 + percent/1).pow(1 * year)
арифметические знаки везде обосабливаются пробелами согласно конвенции стиля в Котлин)

2023-09-12 15:26 UTC, ievetrov commented on src/main/kotlin/lesson_2/lesson_2_task5.kt
> +    println(sumFinale)
согласно ТЗ вывод должен содержать не более 3 знаков после точки

2023-09-12 19:11 UTC, ievetrov requested changes

2023-09-12 19:11 UTC, ievetrov commented on src/main/kotlin/lesson_2/lesson_2_task5.kt
> +    println(sumFinale)
отлично, но это еще не поправлено)
предлагаю использовать уже знакомый String.format()

2023-09-12 19:21 UTC, iarimx commented
Мы просто так не сдаёмся!!!

2023-09-13 06:36 UTC, ievetrov approved these changes
отличный шаблон!
да, и в `1 * year` единичка тоже лишняя, можно удалить

2023-09-13 06:36 UTC, ievetrov commented
> Мы просто так не сдаёмся!!!

поддерживаю!)

2023-09-13 10:21 UTC, merged